In [1]:
from __future__ import print_function
import torch

In [2]:
#Create a 5x3 matrix uninitialized
x=torch.empty(5,3)
print(x)

tensor([[2.5630e-12, 1.4586e-19, 8.2990e-33],
        [1.3563e-19, 1.3563e-19, 1.3563e-19],
        [1.3563e-19, 1.3563e-19, 1.3563e-19],
        [1.3563e-19, 1.4587e-19, 3.8188e-05],
        [8.1546e-33, 1.3563e-19, 1.6114e-19]])


In [3]:
#create randomly initialized matrix
x=torch.rand(5,3)
print(x)

tensor([[0.2466, 0.6562, 0.4628],
        [0.1012, 0.4955, 0.6461],
        [0.0370, 0.4886, 0.8387],
        [0.9531, 0.8834, 0.2893],
        [0.1369, 0.6950, 0.9006]])


In [7]:
#create matrix filled with zero and dtype long
x=torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
#create tensor directly from data
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
#creating tensor based on existing tensor. These methods will resue properties of input tensor, unless values are provided by user
x=x.new_ones(5,3, dtype=torch.double)
print(x)
x=torch.randn_like(x, dtype=torch.float)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3102, -0.1230,  0.2556],
        [-0.6251, -0.4885,  0.3786],
        [ 0.2837,  1.1359,  1.1989],
        [ 2.4436, -1.8641,  1.6703],
        [-0.4124, -0.9033, -0.0213]])


# Addition operation

In [12]:
#syntax 1
y=torch.rand(5,3)
print(x+y)

tensor([[ 1.8878e+00,  4.4207e-02,  1.0281e+00],
        [-2.3617e-01, -6.3447e-02,  4.3442e-01],
        [ 1.1649e+00,  2.0293e+00,  1.6878e+00],
        [ 2.8159e+00, -1.7029e+00,  2.5846e+00],
        [ 1.5128e-03, -8.3406e-01,  2.5271e-01]])


In [13]:
#syntax 2
print(torch.add(x,y))

tensor([[ 1.8878e+00,  4.4207e-02,  1.0281e+00],
        [-2.3617e-01, -6.3447e-02,  4.3442e-01],
        [ 1.1649e+00,  2.0293e+00,  1.6878e+00],
        [ 2.8159e+00, -1.7029e+00,  2.5846e+00],
        [ 1.5128e-03, -8.3406e-01,  2.5271e-01]])


In [14]:
#providing an output tensor as an argument
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.8878e+00,  4.4207e-02,  1.0281e+00],
        [-2.3617e-01, -6.3447e-02,  4.3442e-01],
        [ 1.1649e+00,  2.0293e+00,  1.6878e+00],
        [ 2.8159e+00, -1.7029e+00,  2.5846e+00],
        [ 1.5128e-03, -8.3406e-01,  2.5271e-01]])


In [16]:
#can use standard numpy like indexing
print(result[:,1])

tensor([ 0.0442, -0.0634,  2.0293, -1.7029, -0.8341])


# Resizing tensor

In [20]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [21]:
#if you have 1 element tensor use .item() to get values as a Python number
x=torch.randn(1)
print(x)
print(x.item())

tensor([-1.3260])
-1.3259804248809814


# Tensor to numpy

In [22]:
#torch tensor to numpy array
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [23]:
#numpy array to torch tensor
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Cuda tensors

In [25]:
#tensors can be moved onto any device using.to method
if torch.cuda.is_available():
    device=torch.device('cuda')
    print(device)
    y=torch.ones_like(x, device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu", torch.double))

cuda
tensor([-0.3260], device='cuda:0')
tensor([-0.3260], dtype=torch.float64)
